//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleNutricionalClient.ServiceRefeicao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Refeicao", Namespace="http://schemas.datacontract.org/2004/07/ControleNutricionalService.Models")]
    [System.SerializableAttribute()]
    public partial class Refeicao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataDeCriacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataDeCriacao {
            get {
                return this.dataDeCriacaoField;
            }
            set {
                if ((this.dataDeCriacaoField.Equals(value) != true)) {
                    this.dataDeCriacaoField = value;
                    this.RaisePropertyChanged("dataDeCriacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefeicao.IServiceRefeicao")]
    public interface IServiceRefeicao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/findall", ReplyAction="http://tempuri.org/IServiceRefeicao/findallResponse")]
        ControleNutricionalClient.ServiceRefeicao.Refeicao[] findall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/findall", ReplyAction="http://tempuri.org/IServiceRefeicao/findallResponse")]
        System.Threading.Tasks.Task<ControleNutricionalClient.ServiceRefeicao.Refeicao[]> findallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/find", ReplyAction="http://tempuri.org/IServiceRefeicao/findResponse")]
        ControleNutricionalClient.ServiceRefeicao.Refeicao find(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/find", ReplyAction="http://tempuri.org/IServiceRefeicao/findResponse")]
        System.Threading.Tasks.Task<ControleNutricionalClient.ServiceRefeicao.Refeicao> findAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/create", ReplyAction="http://tempuri.org/IServiceRefeicao/createResponse")]
        bool create(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/create", ReplyAction="http://tempuri.org/IServiceRefeicao/createResponse")]
        System.Threading.Tasks.Task<bool> createAsync(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/edit", ReplyAction="http://tempuri.org/IServiceRefeicao/editResponse")]
        bool edit(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/edit", ReplyAction="http://tempuri.org/IServiceRefeicao/editResponse")]
        System.Threading.Tasks.Task<bool> editAsync(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/delete", ReplyAction="http://tempuri.org/IServiceRefeicao/deleteResponse")]
        bool delete(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRefeicao/delete", ReplyAction="http://tempuri.org/IServiceRefeicao/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRefeicaoChannel : ControleNutricionalClient.ServiceRefeicao.IServiceRefeicao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRefeicaoClient : System.ServiceModel.ClientBase<ControleNutricionalClient.ServiceRefeicao.IServiceRefeicao>, ControleNutricionalClient.ServiceRefeicao.IServiceRefeicao {
        
        public ServiceRefeicaoClient() {
        }
        
        public ServiceRefeicaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRefeicaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRefeicaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRefeicaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ControleNutricionalClient.ServiceRefeicao.Refeicao[] findall() {
            return base.Channel.findall();
        }
        
        public System.Threading.Tasks.Task<ControleNutricionalClient.ServiceRefeicao.Refeicao[]> findallAsync() {
            return base.Channel.findallAsync();
        }
        
        public ControleNutricionalClient.ServiceRefeicao.Refeicao find(string id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<ControleNutricionalClient.ServiceRefeicao.Refeicao> findAsync(string id) {
            return base.Channel.findAsync(id);
        }
        
        public bool create(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao) {
            return base.Channel.create(refeicao);
        }
        
        public System.Threading.Tasks.Task<bool> createAsync(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao) {
            return base.Channel.createAsync(refeicao);
        }
        
        public bool edit(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao) {
            return base.Channel.edit(refeicao);
        }
        
        public System.Threading.Tasks.Task<bool> editAsync(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao) {
            return base.Channel.editAsync(refeicao);
        }
        
        public bool delete(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao) {
            return base.Channel.delete(refeicao);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(ControleNutricionalClient.ServiceRefeicao.Refeicao refeicao) {
            return base.Channel.deleteAsync(refeicao);
        }
    }
}
